version: '3.4'

services:
  backendinternv2:
    image: api
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NODE_ENV: production
    environment:
      - MONGOIP=mongodb
      - MONGOPORT=27017
      - MONGOUSER=admin
      - MONGOPASS=123456
      - DBNAME=deskplus
    ports:
      - 3000:3000
    links:
      - mongo
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://admin:123456@mongodb:27017/

volumes:
  data: